services:
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass asd
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: proxy_user
      POSTGRES_PASSWORD: proxy_password
      POSTGRES_DB: proxy_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  proxy-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=postgres://proxy_user:proxy_password@postgres:5432/proxy_db?sslmode=disable
    depends_on:
      - redis
      - postgres

volumes:
  pgdata: